name: 'itential-automation-status'
description: 'Action to monitor Itential Automation Platform(IAP) automations status and return output variables'
author: 'Itential'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  IAP_INSTANCE:
    description: 'Itential Automation Platform instance url'
    required: true
  IAP_TOKEN:
    description: 'Token required to access IAP instance'
    required: true
  JOB_ID:
    description: 'Job ID to check status of the automation'
    required: true
  TIME_INTERVAL:
    description: 'Time interval to check automation status'
    default: '15'
  NO_OF_ATTEMPTS:
    description: 'No. of attempts to check automation status'
    default: '10'

outputs:
  results: 
    description: 'Return automation details with output variables'

runs:
  using: 'node16'
  main: 'dist/index.js'

