name: 'itential-automation-get-status'
description: 'Action to monitor Itential automation status and return output variables'
author: 'Itential'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
 itential_host_url:
    description: 'Itential instance url'
    required: true
  auth_token:
    description: 'Token is required, if using static token authentication to access Itential instance'
    default: ''
  auth_username:
    description: 'Username is required, if using basic token authentication to access Itential instance'
    default: ''
  auth_password:
    description: 'Password is required, if using basic token authentication to access Itential instance'
    default: ''
  auth_client_id:
    description: 'Client ID is required, if using OAuth2 client credentials authentication to access Itential instance'
    default: ''
  auth_client_secret:
    description: 'Client Secret is required, if using OAuth2 client credentials authentication to access Itential instance'
    default: ''
  automation_id:
    description: 'Automation ID to check status of the automation'
    required: true
  time_interval:
    description: 'Time interval to check automation status'
    default: '15'
  no_of_attempts:
    description: 'No. of attempts to check automation status'
    default: '10'

outputs:
  results: 
    description: 'Return automation details with output variables'

runs:
  using: 'node16'
  main: 'dist/index.js'

