name: 'itential-automation-status'
description: 'Action to monitor Itential Automation Platform(IAP) automations status and return output variables'
author: 'Itential'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  iap_instance:
    description: 'Itential Automation Platform instance url'
    required: true
  iap_token:
    description: 'Token required to access IAP instance'
    required: true
  automation_id:
    description: ' Automation ID to check status of the automation'
    required: true
  time_interval:
    description: 'Time interval to check automation status'
    default: '60'
  no_of_attempts:
    description: 'No. of attempts to check automation status'
    default: '200'

outputs:
  results: 
    description: 'Return automation details with output variables'

runs:
  using: 'node16'
  main: 'dist/index.js'

